version: 2
jobs:
  build:
    docker:
    - image: cirrusci/flutter
    steps:
    - checkout
    - run: flutter doctor
    - run: sdkmanager --update && yes | sdkmanager --licenses
    - run: flutter test
    - run: flutter -v build apk